<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Category facet</name>
   <tag></tag>
   <elementGuidId>b0c13a54-9426-4baa-931d-58f218ea19d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Category facet.']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Category\ facet\.&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1706c8a2-e90a-4df4-826a-04594ab0af65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coveo-facet-header-title</value>
      <webElementGuid>1f3eb9ef-0ea0-4d11-9e3f-f4e054b3a38a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>ee2feb98-a36b-4c18-b005-6bdf67cedc22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e2d1f9df-670d-4a2a-9fbe-7ec2c41f5f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Category facet.</value>
      <webElementGuid>a30e6623-862d-4139-83d5-bfcf30f06434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Category facet</value>
      <webElementGuid>a86b5644-3a0d-4502-a658-0950c0cb4c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Category</value>
      <webElementGuid>8d693d6f-f029-40c9-9b8b-bec33c63e721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4f6b1315b6558326113aebde2bb0f588</value>
      <webElementGuid>8af82cb6-ac35-4039-b0f7-225fd26647f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Category facet.']</value>
      <webElementGuid>23bd1230-f56e-4e3f-9166-659994f28e6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Category facet.']</value>
      <webElementGuid>2acd62da-c3d1-4fbb-81c7-2c85b4fd5a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Category facet' or . = 'Category facet')]</value>
      <webElementGuid>974f1e20-adbe-4858-8e19-28e9c13ad965</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
