<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ToggleAppExchange168</name>
   <tag></tag>
   <elementGuidId>915beb0c-3c95-4ead-9b00-6110f82e778e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-original-value=&quot;AppExchange&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-original-value = 'AppExchange']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>79b28d4c-c3a2-411d-a4d8-fe1a763e868f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coveo-facet-value-caption</value>
      <webElementGuid>ba6bb3d8-33ad-4ee9-b8a0-4fedeb817c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>AppExchange</value>
      <webElementGuid>36436e88-c0cd-4edf-9934-e8ccb4c1a236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-value</name>
      <type>Main</type>
      <value>AppExchange</value>
      <webElementGuid>b046eb88-1b92-4c74-b371-4df593abd9c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ToggleAppExchange168</value>
      <webElementGuid>419a94ed-1c6b-4a2f-a830-7353260c29b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>AppExchange</value>
      <webElementGuid>6f52d31b-fa5b-40ba-a77a-1a5cd8b02d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-41087c99f262de60eab9a5101f2fb851</value>
      <webElementGuid>cd8da636-3722-4ca4-a6a2-46d905598e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-original-value = 'AppExchange']</value>
      <webElementGuid>329d9013-cb51-4bf6-b1f4-a5c859f9a40e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-original-value = 'AppExchange']</value>
      <webElementGuid>ece28f9f-d993-4d6d-aabf-72ebeaf7068c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'AppExchange' and (text() = 'ToggleAppExchange168' or . = 'ToggleAppExchange168')]</value>
      <webElementGuid>5cc7249e-875d-4ed8-8331-c614d4909270</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
