<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ToggleExperience4,634</name>
   <tag></tag>
   <elementGuidId>6b39fd81-e670-480b-b16d-1baa1a3f7fdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-original-value=&quot;Experience&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-original-value = 'Experience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>666b1af8-2c78-4085-8029-e7f7c37cdbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coveo-facet-value-caption</value>
      <webElementGuid>1ac15721-85b1-4862-8af4-2a2b34e0ad82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Experience</value>
      <webElementGuid>5c0d95c1-a1cf-4ee6-b2ab-a83737a9c960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-value</name>
      <type>Main</type>
      <value>Experience</value>
      <webElementGuid>af13351c-ad88-4545-b98d-03ccd9657f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ToggleExperience4,634</value>
      <webElementGuid>87e1c83a-4c52-45ca-8503-d5eab07517fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Experience</value>
      <webElementGuid>8146a5a7-0a97-4527-82e2-a04cbb8778df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-9069511dac344947e5cab68d643b5c6c</value>
      <webElementGuid>abd49e92-3edd-4e41-b4d4-c64527e5961f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-original-value = 'Experience']</value>
      <webElementGuid>9d952fc5-1d89-47db-9304-17b086de9425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-original-value = 'Experience']</value>
      <webElementGuid>51669e47-c730-4ea2-b33f-8bee807a5989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Experience' and (text() = 'ToggleExperience4,634' or . = 'ToggleExperience4,634')]</value>
      <webElementGuid>a1b5a3b6-8e92-4c0d-a11c-53cc76f5ec0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
