<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_ToggleAppExchange168</name>
   <tag></tag>
   <elementGuidId>93671cdc-aeca-47a7-9e69-f963f1ad12a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(@aria-label = 'Inclusion filter on AppExchange; 168 results') and @class and contains(concat(' ', normalize-space(@class), ' '), ' coveo-facet-value-checkbox ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' coveo-facet-value-checkbox-svg ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Inclusion\ filter\ on\ AppExchange\;\ 168\ results&quot;].coveo-facet-value-checkbox .coveo-facet-value-checkbox-svg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>76a5b877-2adc-4c18-8255-9337baff76a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Toggle</value>
      <webElementGuid>1ed5312b-aba5-44ec-8ac2-5e0151368d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>02d6716a-3c71-4536-9db9-b64e2ec6b2c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>47f3fe4c-d554-4f02-93ed-81195a7b3a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 11 11</value>
      <webElementGuid>212a2828-26b7-40fd-b052-e8f1b6e5346e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coveo-facet-value-checkbox-svg</value>
      <webElementGuid>0e54b597-efef-444a-9d96-dbb9c72ae32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ToggleAppExchange168</value>
      <webElementGuid>bc0ba91a-6baf-45cc-acae-a006c3053c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-c06768a1cf7bb11936305880033ae5a1</value>
      <webElementGuid>8ed25ecd-b402-48c8-a988-4827f80e2d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@aria-label = 'Inclusion filter on AppExchange; 168 results') and @class and contains(concat(' ', normalize-space(@class), ' '), ' coveo-facet-value-checkbox ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' coveo-facet-value-checkbox-svg ')]</value>
      <webElementGuid>41865068-8349-4d8d-b6ae-b8447bb86610</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@aria-label = 'Inclusion filter on AppExchange; 168 results') and @class and contains(concat(' ', normalize-space(@class), ' '), ' coveo-facet-value-checkbox ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' coveo-facet-value-checkbox-svg ')]</value>
      <webElementGuid>c2c74eb9-7c8f-4594-a7bb-f78c9ce21032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[(text() = 'ToggleAppExchange168' or . = 'ToggleAppExchange168')]</value>
      <webElementGuid>1176d498-a05c-47a6-854b-6a4160c840ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
