<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_md-input-2mimmh1s</name>
   <tag></tag>
   <elementGuidId>47c06632-6e1f-4ce4-81e8-90910868ba87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='md-input-2mimmh1s']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#md-input-2mimmh1s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4eafad96-21cd-4e01-a383-caf5af9d416d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6135493c-b9de-4973-9139-41244566c160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>md-input-2mimmh1s</value>
      <webElementGuid>27262426-130d-4dd0-93d0-d649b3d34360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-input</value>
      <webElementGuid>96c970fa-0ac0-46a7-be1c-b767fe87de11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;md-input-2mimmh1s&quot;)</value>
      <webElementGuid>c46d4d6c-5265-408a-b6ef-6c5ec968b8ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='md-input-2mimmh1s']</value>
      <webElementGuid>03aff4e2-feb1-4147-a0e0-efce2d7626f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>cb7c1dd4-1a21-4f54-b2d1-634dd16dd4bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2ed38bd4-7983-4041-8d82-6da741a41ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'md-input-2mimmh1s']</value>
      <webElementGuid>0d111910-79d2-4700-9815-a42a8f6de11e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
