<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_md-input-77d4ddoki</name>
   <tag></tag>
   <elementGuidId>5a722f68-47f8-4574-9130-be67384b4567</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='md-input-77d4ddoki']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#md-input-77d4ddoki</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>681d31e3-2e04-4a05-bff6-5e73865821e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8c030677-0264-4d9b-8b7d-4cd648d40d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>md-input-77d4ddoki</value>
      <webElementGuid>53c88955-c7a4-4706-85d4-6466f006e9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-input</value>
      <webElementGuid>13bf03d4-7c29-4be8-b7bc-1ba1565f3910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;md-input-77d4ddoki&quot;)</value>
      <webElementGuid>514a186f-650d-4c81-a975-11e418f1cea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='md-input-77d4ddoki']</value>
      <webElementGuid>2f906fea-0ad9-4fad-b319-6ab3a73fac6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/div[2]/div/div[2]/div/div/div[2]/input</value>
      <webElementGuid>19fc9b48-cc66-4b67-86f5-fe923ea507fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>70f34f2e-9a4d-4aec-97c7-8ba5644cd7f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'md-input-77d4ddoki']</value>
      <webElementGuid>561a2ae4-32f9-4a7d-95ce-2eebf9339b66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
