<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Username-input</name>
   <tag></tag>
   <elementGuidId>ec907e8f-3240-421c-b3be-17942b3ad70a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='md-input-li9r4l4fp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#md-input-li9r4l4fp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab6407f3-98a7-4c29-824a-6f9e0720f6d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9f51d84-96a2-4667-b28b-2e628c56fd0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>md-input-li9r4l4fp</value>
      <webElementGuid>b49c889c-d360-4f0f-be3d-e5610b3dec0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>md-input</value>
      <webElementGuid>a301d8c7-f202-4742-8a87-e452f0a12d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;md-input-li9r4l4fp&quot;)</value>
      <webElementGuid>db431393-d29a-408a-80e8-f2ed359913a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='md-input-li9r4l4fp']</value>
      <webElementGuid>e3951356-28c2-4d2f-a302-b816c17a27dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/main/div/div[2]/div/div[2]/div/div/div/input</value>
      <webElementGuid>623f6f70-fef3-4e18-a95c-ede4c0b5e7e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>57f5f50a-e548-416e-8c9d-f0d87f8402e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'md-input-li9r4l4fp']</value>
      <webElementGuid>cbc8dd5f-17b9-4e7e-b118-acaa658a8609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
