<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_More</name>
   <tag></tag>
   <elementGuidId>5565da82-66a7-468a-b592-48d94cc7b1de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ember12']/div/div/div[2]/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.widget-link.filter.search-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>996c9caf-5d7f-4971-9670-82bff3952434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>widget-link filter search-link</value>
      <webElementGuid>5ec6e7c6-089b-4ebe-bac2-1ed285a80abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/search?q=webdriver</value>
      <webElementGuid>01605bd3-55cf-449e-847c-2e283d51f3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>More...</value>
      <webElementGuid>f8eaf879-0617-42e0-814f-9e58954021b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember12&quot;)/div[@class=&quot;search-widget&quot;]/div[@class=&quot;search-menu&quot;]/div[@class=&quot;results&quot;]/div[@class=&quot;search-result-topic&quot;]/div[@class=&quot;show-more&quot;]/a[@class=&quot;widget-link filter search-link&quot;]</value>
      <webElementGuid>30855bfa-4b25-4c7f-b384-7ab27cfab378</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember12']/div/div/div[2]/div/div/a</value>
      <webElementGuid>97afd331-891e-40a5-a0d9-5225ff69310e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[5]/following::a[1]</value>
      <webElementGuid>11a223f6-0b4b-4edb-8521-fd96327e9296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Aug ', &quot;'&quot;, '18')])[1]/following::a[1]</value>
      <webElementGuid>2767ed12-bcfc-4fc7-a6b5-690c9fef5d46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DETAIL YOUR QUESTIONS'])[1]/preceding::a[1]</value>
      <webElementGuid>3c377ca8-730e-48b5-be86-336f562280f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='More']/parent::*</value>
      <webElementGuid>c5dbd6e1-004a-474f-8148-b4fd1ef67587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/search?q=webdriver')])[2]</value>
      <webElementGuid>4b20c777-9c27-42c4-b441-a50611ab51ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>22cf1269-1ffc-4c1e-a231-6d2ee5ab7526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/search?q=webdriver' and (text() = 'More...' or . = 'More...')]</value>
      <webElementGuid>5ada4611-8553-43d1-9df8-e2eb730e9184</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
