<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome to Katalon Community_search-term</name>
   <tag></tag>
   <elementGuidId>5a3eef78-3cd6-4c7b-be52-96d6c66d51ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'search-term' and @type = 'text' and @placeholder = 'Search']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-term']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search-term</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27ae8d6d-e2e4-4f9f-84e4-ab7784360d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-term</value>
      <webElementGuid>2ae5aaee-37f3-4215-a723-a41dce8f5540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a4fdacb-f9d2-480f-a001-0775c2ce4f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2168b28c-0233-4bd9-a0a8-b360c5f0192e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>d6d02314-1b5e-4fa5-bc38-cf1b7e7e1282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>feba270f-750b-47cb-85af-6e9bd3e9400f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-term&quot;)</value>
      <webElementGuid>21990221-495c-4b25-95c7-87957866f3dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-term']</value>
      <webElementGuid>6b179893-d816-4926-bbca-bdf656224e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember12']/div/div/div/input</value>
      <webElementGuid>d6ae8529-c5bd-4ea1-8d27-01c5abebc8a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d9ea317a-aee2-4311-870c-d20c2c9566a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search-term' and @type = 'text' and @placeholder = 'Search']</value>
      <webElementGuid>95b7197d-d1e9-40a8-bbb6-e64a9f19fe5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
