<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_in all topics and posts</name>
   <tag></tag>
   <elementGuidId>97ea92d7-6868-423a-aebc-05d356895dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ember12']/div/div/div[2]/ul/li/a/span/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.label-suffix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a9da274f-78f1-4359-b7f4-70311a2548eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-suffix</value>
      <webElementGuid>a58b3827-b467-4545-8705-8fdeaf4ef81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>in all topics and posts</value>
      <webElementGuid>80ac49d9-1f3c-4695-af5b-4444cf7f3688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember12&quot;)/div[@class=&quot;search-widget&quot;]/div[@class=&quot;search-menu&quot;]/div[@class=&quot;results&quot;]/ul[@class=&quot;search-menu-initial-options&quot;]/li[@class=&quot;search-menu-assistant-item&quot;]/a[@class=&quot;widget-link search-link&quot;]/span[@class=&quot;search-item-slug&quot;]/span[@class=&quot;label-suffix&quot;]</value>
      <webElementGuid>f2b0fa1c-7afb-4956-928d-f21c440b7f0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember12']/div/div/div[2]/ul/li/a/span/span[2]</value>
      <webElementGuid>5bf0b1a6-f89e-4bd3-97e9-54f8a336f339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='webdriver'])[1]/following::span[1]</value>
      <webElementGuid>c6395184-a075-4852-9017-78f842614ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to Katalon Community!'])[1]/following::span[3]</value>
      <webElementGuid>d997ae5a-53f8-47ed-94ac-f5e75ef531a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or press Enter'])[1]/preceding::span[1]</value>
      <webElementGuid>039d86c4-4e3e-433c-96b2-f0ef89c54f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='webdriver'])[2]/preceding::span[2]</value>
      <webElementGuid>4b1f4954-7de4-43bb-b735-96ce092ffb8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='in all topics and posts']/parent::*</value>
      <webElementGuid>d1ae803a-7fe3-4bc8-ada5-d3e0361fe8da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span[2]</value>
      <webElementGuid>e382ad63-0021-4c9f-9b02-4e370e8e7755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'in all topics and posts' or . = 'in all topics and posts')]</value>
      <webElementGuid>8a806b32-b02c-4b46-b541-ead294c5c6d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
