<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_alternative link_popup_back</name>
   <tag></tag>
   <elementGuidId>4064a05f-3763-493f-a7e6-4beed1260f6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='form-homepage-popup']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-homepage-popup > div.popup_back</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0f629395-2919-4d46-ae63-e61228366bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup_back</value>
      <webElementGuid>0498976c-b968-42ff-903c-dbbb1eb2018b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-homepage-popup&quot;)/div[@class=&quot;popup_back&quot;]</value>
      <webElementGuid>b5fa4964-e9bb-4b1f-88a6-f9da921eeb03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-homepage-popup']/div[2]</value>
      <webElementGuid>1df71daa-aab0-4d85-ba15-3cdf7e81ee86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]</value>
      <webElementGuid>60979dbb-3ac2-4457-ac35-22c90e4d64bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
