<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Example_div1</name>
   <tag></tag>
   <elementGuidId>2094a392-6c26-4f57-82d3-a4249578f9b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>04762399-aebe-4ee5-bfb7-fb253ce3752d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div1</value>
      <webElementGuid>4b4a32e8-e4de-4b64-a59a-cf77da89dca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondrop</name>
      <type>Main</type>
      <value>drop(event)</value>
      <webElementGuid>f41720ed-f856-4242-aff1-9312dad4e26b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondragover</name>
      <type>Main</type>
      <value>allowDrop(event)</value>
      <webElementGuid>7baf4550-7ddb-4e8a-9b3e-66f95cd995aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div1&quot;)</value>
      <webElementGuid>626f455a-3e23-442b-b5e4-77c32b49ca8f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div1']</value>
      <webElementGuid>499bfa1c-9429-4ab8-98a1-a2f974eb50dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[3]</value>
      <webElementGuid>e18f0fce-28fc-41e0-ba33-a03447fea1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Example'])[1]/following::div[1]</value>
      <webElementGuid>5d40d3a1-0a00-402f-91de-4b9b7712565b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next ❯'])[1]/following::div[1]</value>
      <webElementGuid>f40d6c5c-b25a-4141-958f-d98ed6d1d273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drag and Drop'])[1]/preceding::div[2]</value>
      <webElementGuid>e0af0537-296f-46a5-9bb2-a7a1032de933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Browser Support'])[1]/preceding::div[2]</value>
      <webElementGuid>5b7069a5-3511-4a32-9c74-e2d4aa9a06a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[3]</value>
      <webElementGuid>5c0cfe75-2aca-4c18-8fa3-e559ae2c70bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'div1']</value>
      <webElementGuid>2585a480-b1cc-435e-9f00-6fd51cac04fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
