<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Example_div2</name>
   <tag></tag>
   <elementGuidId>815ded21-9c8e-4bff-a5f4-b0a67fe46004</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#div2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7707b218-b63b-485f-865e-b1adfd551aa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>div2</value>
      <webElementGuid>22bf3155-ef5e-4d33-be9f-e7b044ad4e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondrop</name>
      <type>Main</type>
      <value>drop(event)</value>
      <webElementGuid>3633382d-88bf-4ea6-8002-87da0be3ff25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondragover</name>
      <type>Main</type>
      <value>allowDrop(event)</value>
      <webElementGuid>c914321d-0d28-4c26-bdcf-f1c2514a733d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div2&quot;)</value>
      <webElementGuid>7845b830-b06c-4d85-b73e-7b6c854f8f2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='div2']</value>
      <webElementGuid>0ce30847-19a3-43bd-9575-f9bd73eaafca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[4]</value>
      <webElementGuid>74b82fb1-70b9-4270-82e3-6d326491c0b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[4]</value>
      <webElementGuid>03af1eb9-2649-4d61-aef7-af629a7fb782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'div2']</value>
      <webElementGuid>0c5b28dd-161c-479c-8dfa-2f2bdd91178f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
