<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Example_drag1</name>
   <tag></tag>
   <elementGuidId>1d261b13-9ce5-49fd-8f03-8c2a07b67740</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='drag1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#drag1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7b1a6ab7-b913-4f65-ba1f-6099135bfdc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>img_w3slogo.gif</value>
      <webElementGuid>d059c7b8-1770-47e7-8fba-bb5c6ec84b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>draggable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ccbc6bd1-ba77-4303-bf2d-a219c62bc5d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondragstart</name>
      <type>Main</type>
      <value>drag(event)</value>
      <webElementGuid>129b7de7-bfcb-4a68-b613-e9dcb67b1630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drag1</value>
      <webElementGuid>086fddb4-0aaa-40b5-ab77-47334433584d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>W3Schools</value>
      <webElementGuid>729245e0-7d5b-4a97-a1e9-d8dee722cfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drag1&quot;)</value>
      <webElementGuid>8d6f9226-3870-4116-b861-ef428ee45f91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='drag1']</value>
      <webElementGuid>19fc154f-e5a8-4dce-95d7-e8ce22d6a871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div1']/img</value>
      <webElementGuid>a7304432-e7a2-4c7a-97cd-bbec4318e77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='W3Schools']</value>
      <webElementGuid>262a62f7-2ee8-4b8e-bc19-283f399aa308</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b0bbdafb-b536-4fff-9c71-49b81691fcf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'img_w3slogo.gif' and @id = 'drag1' and @alt = 'W3Schools']</value>
      <webElementGuid>0513deab-3207-489a-bd98-cea49d2e709c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
