<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Studio_logo</name>
   <tag></tag>
   <elementGuidId>11277335-09eb-4815-87c7-fd7f2b1dd172</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hs_cos_wrapper_module_67782580076']/div[7]/div/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.prod-ks.product > img.logo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0cea8c66-ecbc-4c4f-998e-4772339c5a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>logo</value>
      <webElementGuid>49b56617-4147-489b-8728-a6c74018f127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/testcloud_landing_page/01_2022/logo-studio.svg</value>
      <webElementGuid>5a34d055-5627-48df-bbf6-f87e93bc2f3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Simple Orchestration</value>
      <webElementGuid>b2500bda-99b8-4257-815e-581aa9cb1569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9552f157-2290-4eb6-8584-478b1fbe69e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hs_cos_wrapper_module_67782580076&quot;)/div[@class=&quot;section-product-guide play_animation&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;div-products&quot;]/div[@class=&quot;prod-ks product&quot;]/img[@class=&quot;logo&quot;]</value>
      <webElementGuid>8b88c0a4-8313-4d53-952f-5f6cae78b13f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hs_cos_wrapper_module_67782580076']/div[7]/div/div/div[2]/img</value>
      <webElementGuid>03fa3e69-f3e2-4237-aa69-e93214dedbd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Simple Orchestration'])[5]</value>
      <webElementGuid>3475cee8-1db1-417e-9ec0-37b813173ce7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/img</value>
      <webElementGuid>5bc3404c-bf20-4446-8f33-43756e5cf7d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1h3p5fzmizjvp.cloudfront.net/themes/katalon_4/images/pages/testcloud_landing_page/01_2022/logo-studio.svg' and @alt = 'Simple Orchestration']</value>
      <webElementGuid>e17fb31c-7832-48c8-9b41-90d3a7d54982</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
