<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__email_testcloud_contact</name>
   <tag></tag>
   <elementGuidId>d0216a7d-5593-4731-aaa4-8ca02923698c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email_testcloud_contact']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email_testcloud_contact</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c93fa554-61f6-4b91-be0f-906edba6a414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>944a4421-0b02-4e18-a496-ecd47a5abaa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_testcloud_contact</value>
      <webElementGuid>3ef15955-bc39-4e7f-b461-f8d7632dfb8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-email</value>
      <webElementGuid>ee8b0a31-817d-4b73-9180-14c16bf58d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_testcloud_contact&quot;)</value>
      <webElementGuid>1c807736-5202-427d-ab9c-d9ce26dcf75d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email_testcloud_contact']</value>
      <webElementGuid>bbdb881b-ab41-4601-824d-53051b666473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-testcloud-trial-submit']/div/div/div/div/div[4]/input</value>
      <webElementGuid>275932c4-0617-4ce7-92f0-b6d63fdfd553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>8bd901e1-df3f-4f5d-aa00-1a9a110b044b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'email_testcloud_contact']</value>
      <webElementGuid>e64889b7-c6a2-466b-bfea-e2e43d326bb6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
