<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fullname_testcloud_contact</name>
   <tag></tag>
   <elementGuidId>04c4017d-ca40-4084-a7b6-4311b8df0846</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fullname_testcloud_contact']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fullname_testcloud_contact</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>279bd4be-4f1d-4530-8d5f-03ead943fb68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>516eee26-325b-4ccf-965b-c0b319a93294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fullname_testcloud_contact</value>
      <webElementGuid>f85c97b4-2e3b-45aa-bf9a-ff9bacab4378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-name</value>
      <webElementGuid>23ad86fe-688a-426c-a4c0-4f81c905c45d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullname_testcloud_contact&quot;)</value>
      <webElementGuid>132741e8-4700-4bea-9883-abc517fc2366</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fullname_testcloud_contact']</value>
      <webElementGuid>8af7f99f-a960-43b1-ada5-03a85bab1b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-testcloud-trial-submit']/div/div/div/div/div[3]/input</value>
      <webElementGuid>be22d516-4563-42a7-9636-8cdce932ea3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>6891e680-9831-408a-8e4e-1a3ee5f8d063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'fullname_testcloud_contact']</value>
      <webElementGuid>f13ef502-7fd3-407a-bfc3-7e456256285a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
