# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-18.04

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: katalonTask@1
  inputs:
    version: '8.4.1'
    executeArgs: 'katalonc -noSplash -runMode=console -projectPath="C:\Users\quan.trinh\Katalon Studio\Introduction Of TestCloud with Katalon Studio\Introduction Of TestCloud with Katalon Studio.prj" -retry=0 -testSuitePath="Test Suites/TS3 - Execute Js" -browserType="IE" -executionProfile="default" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
