<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_show-on-hover absolute fill hide-for-small b</name>
   <tag></tag>
   <elementGuidId>4c807c6c-d136-432f-a7af-503365e1eff8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[href=&quot;https\:\/\/nhuaquankiet\.com\/san-pham\/nap-nhua-lon-thiec-lon-sua-lon-pate\/&quot;] img.show-on-hover.hide-for-small.back-image.fill[loading=&quot;lazy&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@href = 'https://nhuaquankiet.com/san-pham/nap-nhua-lon-thiec-lon-sua-lon-pate/']//img[@class and contains(concat(' ', normalize-space(@class), ' '), ' show-on-hover ') and contains(concat(' ', normalize-space(@class), ' '), ' hide-for-small ') and contains(concat(' ', normalize-space(@class), ' '), ' back-image ') and contains(concat(' ', normalize-space(@class), ' '), ' fill ') and (@loading = 'lazy')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b32beb3b-f9b8-4fa4-8dd9-52fde7a8d42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>7b57879d-826f-4403-9f79-a81ef82f7b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>600</value>
      <webElementGuid>2a027c80-d873-45c6-9a5d-a91477930c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://nhuaquankiet.com/wp-content/uploads/2024/01/nap-nhua-quan-kiet.jpg</value>
      <webElementGuid>741739d9-eb75-4e32-a4e4-6cc71314358f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>show-on-hover absolute fill hide-for-small back-image</value>
      <webElementGuid>659842e6-dc69-435b-a6f7-8b897f101802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>27452b60-a5fb-48f9-9e1d-209fe471388e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>0ba580d2-1b8c-44a1-a447-de92a73e72b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://nhuaquankiet.com/wp-content/uploads/2024/01/nap-nhua-quan-kiet.jpg 600w, https://nhuaquankiet.com/wp-content/uploads/2024/01/nap-nhua-quan-kiet-400x400.jpg 400w, https://nhuaquankiet.com/wp-content/uploads/2024/01/nap-nhua-quan-kiet-280x280.jpg 280w, https://nhuaquankiet.com/wp-content/uploads/2024/01/nap-nhua-quan-kiet-100x100.jpg 100w</value>
      <webElementGuid>fb41f000-5b00-4ac7-8ac6-1f5a4b467f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 600px) 100vw, 600px</value>
      <webElementGuid>d2c6e2b4-752c-4269-936e-d05888f1af84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>show-on-hover absolute fill hide-for-small b</value>
      <webElementGuid>7b7f2544-b387-43d9-946f-f36569ac0ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-91bdfde43adb88caeb2734deb89e99d9</value>
      <webElementGuid>6ca5fde3-1288-4355-82dc-52f3a7f98afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href = 'https://nhuaquankiet.com/san-pham/nap-nhua-lon-thiec-lon-sua-lon-pate/']//img[@class and contains(concat(' ', normalize-space(@class), ' '), ' show-on-hover ') and contains(concat(' ', normalize-space(@class), ' '), ' hide-for-small ') and contains(concat(' ', normalize-space(@class), ' '), ' back-image ') and contains(concat(' ', normalize-space(@class), ' '), ' fill ') and (@loading = 'lazy')]</value>
      <webElementGuid>8aa9f981-c8e0-44e5-acdf-9f22653eeb29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@href = 'https://nhuaquankiet.com/san-pham/nap-nhua-lon-thiec-lon-sua-lon-pate/']//img[@class and contains(concat(' ', normalize-space(@class), ' '), ' show-on-hover ') and contains(concat(' ', normalize-space(@class), ' '), ' hide-for-small ') and contains(concat(' ', normalize-space(@class), ' '), ' back-image ') and contains(concat(' ', normalize-space(@class), ' '), ' fill ') and (@loading = 'lazy')]</value>
      <webElementGuid>10351291-079c-43d0-89c8-69bb5906152e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://nhuaquankiet.com/wp-content/uploads/2024/01/nap-nhua-quan-kiet.jpg' and (text() = 'show-on-hover absolute fill hide-for-small b' or . = 'show-on-hover absolute fill hide-for-small b')]</value>
      <webElementGuid>c4596aee-e330-4177-8c05-cb6afc318198</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
