<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Cases</name>
   <tag></tag>
   <elementGuidId>6a73de36-3965-4d37-9b9a-2429bdf85c40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Console'])[3]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.slds-context-bar__label-action.slds-p-left--xx-small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>86a7cf54-99e8-4110-89ba-430f0310fd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lightning/o/Case/list?filterName=00BRA000001fegr2AA</value>
      <webElementGuid>9553b110-d1c4-4c04-bb13-322bcfdc95c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-context-bar__label-action slds-p-left--xx-small</value>
      <webElementGuid>36e0dd7b-9fdb-414e-ba3c-4f75448c5915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>361:0;p</value>
      <webElementGuid>2520e594-32ff-4f93-955b-2832efc5b2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cases</value>
      <webElementGuid>1b6a5ca5-62d4-4a39-9720-471847777ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cases</value>
      <webElementGuid>f684c697-22d8-42e9-b6b0-9511bc94d824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;desktop slds-wcag&quot;]/div[@class=&quot;desktop container forceStyle oneOne navexDesktopLayoutContainer lafAppLayoutHost forceAccess tablet&quot;]/div[@class=&quot;viewport&quot;]/section[@class=&quot;layoutContent stage panelSlide hasFixedFooter&quot;]/div[@class=&quot;workspaceManager navexWorkspaceManager&quot;]/div[@class=&quot;oneConsoleTabset navexConsoleTabset&quot;]/div[@class=&quot;tabsetHeader slds-context-bar slds-context-bar--tabs slds-no-print&quot;]/div[@class=&quot;slds-context-bar__primary navLeft navBar&quot;]/div[@class=&quot;oneConsoleNav navexConsoleNav&quot;]/div[@class=&quot;selectedListItem slds-col--bump-left slds-p-left--x-small slds-context-bar__item slds-context-bar__object-switcher&quot;]/a[@class=&quot;slds-context-bar__label-action slds-p-left--xx-small&quot;]</value>
      <webElementGuid>536b8433-429f-4ef7-8766-96e54348149f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Console'])[3]/following::a[1]</value>
      <webElementGuid>f71c36f4-1277-4bcf-a43a-b4fe305bc4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='App Launcher'])[1]/following::a[1]</value>
      <webElementGuid>8b110f42-32ab-4e14-9ff9-ffa5064fd9b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Navigation Menu'])[1]/preceding::a[1]</value>
      <webElementGuid>42c9ef15-2691-4719-9abf-93493a70a701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lightning/o/Case/list?filterName=00BRA000001fegr2AA')]</value>
      <webElementGuid>e471ede3-5d17-4c2f-8bf7-7f993f442757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>1d9f97f1-66cb-4ce3-ab11-35ec6515bc8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/lightning/o/Case/list?filterName=00BRA000001fegr2AA' and @title = 'Cases' and (text() = 'Cases' or . = 'Cases')]</value>
      <webElementGuid>3079cb2c-71b3-421e-872c-df7fe18aa50c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
