<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Note_image img_E7b_ medium-zoom-image</name>
   <tag></tag>
   <elementGuidId>9dbd4b4e-847f-4c50-8a8e-dd71d2d91ad2</elementGuidId>
   <imagePath>../../Desktop/define_image.png</imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__docusaurus']/div[2]/div/main/div/div/div/div/article/div[2]/div[2]/p[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.image.img_E7b_.medium-zoom-image</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>../../Desktop/define_image.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>IMAGE</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>85d5ffda-16a1-4d45-ae82-68c5673b7bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>3f72c333-6684-4ad0-a3ab-e362f01e0731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image img_E7b_ medium-zoom-image</value>
      <webElementGuid>dba2edf2-2fc7-4460-955c-0e114a1ceeae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://github.com/katalon-studio/docs-images/raw/master/katalon-studio/docs/webui-verify-image-present/define_image.jpg</value>
      <webElementGuid>13595293-220e-4c71-bfe7-1de3272ca35f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__docusaurus&quot;)/div[@class=&quot;main-wrapper docsWrapper_mKqt&quot;]/div[@class=&quot;docPage_ualW&quot;]/main[@class=&quot;docMainContainer_uL0j&quot;]/div[@class=&quot;container padding-top--md padding-bottom--lg&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col docItemCol_nDMA&quot;]/div[@class=&quot;docItemContainer_p3Qu&quot;]/article[1]/div[@class=&quot;theme-doc-markdown markdown&quot;]/div[@class=&quot;note note note_note&quot;]/p[@class=&quot;p&quot;]/img[@class=&quot;image img_E7b_ medium-zoom-image&quot;]</value>
      <webElementGuid>b7db9bb3-20e8-4537-9227-618ba234b029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__docusaurus']/div[2]/div/main/div/div/div/div/article/div[2]/div[2]/p[2]/img</value>
      <webElementGuid>749be30f-c445-45a8-a180-26bad7b04463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://github.com/katalon-studio/docs-images/raw/master/katalon-studio/docs/webui-verify-image-present/define_image.jpg')]</value>
      <webElementGuid>fd11ee21-9b83-4e5c-8401-0e09c9652d05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/img</value>
      <webElementGuid>36cddf2e-4e53-49f6-a4e9-cf51e25e3e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://github.com/katalon-studio/docs-images/raw/master/katalon-studio/docs/webui-verify-image-present/define_image.jpg']</value>
      <webElementGuid>f2240c63-8667-4045-8924-81a0272fdd70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
