<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Being free from pain</name>
   <tag></tag>
   <elementGuidId>cba3ffb6-6347-46b3-901c-9e28d2f19889</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sq_100']/div[2]/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.sjs-sortablejs-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e615a2b8-eb0e-471a-ad11-9459b82720a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sjs-sortablejs-item</value>
      <webElementGuid>a6863538-6ca3-4ed6-b92d-5f1f83007b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>7598aba1-9438-40f6-abdf-38b5bb227083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Being free from pain</value>
      <webElementGuid>12902cb6-d53d-4758-9973-5b6d31476d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sq_100&quot;)/div[@class=&quot;sv_q_content q-icon-small&quot;]/div[@class=&quot;sjs-sortablejs-root&quot;]/div[@class=&quot;sjs-sortablejs-source&quot;]/div[@class=&quot;sjs-sortablejs-item&quot;]</value>
      <webElementGuid>f72952d4-7777-486a-ab9e-bb48b366bd64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sq_100']/div[2]/div/div[3]/div</value>
      <webElementGuid>db9dab65-036a-4bd1-bb60-ced30b11240a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select (drag) one or more items listed below to this section'])[1]/following::div[2]</value>
      <webElementGuid>07b7bc33-5faa-4baf-b855-b20b6125945a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What is important to you?'])[1]/following::div[8]</value>
      <webElementGuid>ac29c788-fd47-45aa-b687-02ccf4a1947c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Being with my family'])[1]/preceding::div[1]</value>
      <webElementGuid>4eb55c17-ee2e-4bd4-a429-94170b1a838a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Being able to feed, bathe, and take care of myself'])[1]/preceding::div[2]</value>
      <webElementGuid>f84ab4e0-c5fa-483b-83ef-e8ded5e6fee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Being free from pain']/parent::*</value>
      <webElementGuid>b117b873-3095-4ea7-a598-61d13af95189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/div[3]/div</value>
      <webElementGuid>722640f9-f211-4719-b13e-5695da83af2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Being free from pain' or . = 'Being free from pain')]</value>
      <webElementGuid>87643970-ddc1-427a-982f-c06427b3a80b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
