<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_My Dislikes  Fears_sq_118i</name>
   <tag></tag>
   <elementGuidId>3f05ec80-f26a-4a3a-8b6d-33dae8558b53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='sq_118i']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sq_118i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>417c7f3d-7c7b-44b7-a5c7-b16e70f29769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sq_118i</value>
      <webElementGuid>a022a450-8a4d-40e9-812a-f993aae94930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>09ff9937-e4e4-4eaf-a5c7-eb645e84e52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>a4e60213-c5b6-495d-80d8-b852c3dfd6c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type here…</value>
      <webElementGuid>fc257ab5-b3f5-443b-982b-42f34aa54a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>76cb825d-80b0-45f0-9210-f82907bcd00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>&lt;strong>My Dislikes / Fears&lt;/strong></value>
      <webElementGuid>2995ad16-3abf-499d-a742-9119f7194512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b3597bea-b03f-4b85-94bc-2ffc3f1fcf09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sq_118i&quot;)</value>
      <webElementGuid>8f45bac6-b336-46c0-9f38-c327edc185eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='sq_118i']</value>
      <webElementGuid>36892318-e787-4073-a820-c4c7963b02a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sq_118']/div[2]/textarea</value>
      <webElementGuid>6f04cb45-9050-4549-be5c-ce16081b0944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/div/form/div[2]/div/div/div[2]/div/div/div[2]/textarea</value>
      <webElementGuid>8f16766c-ee02-4c20-a695-0f348789befa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'sq_118i' and @placeholder = 'Type here…']</value>
      <webElementGuid>ad1f08eb-da62-4d9b-8ee7-8d2acf586c8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
