<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_My Unfinished Business_sq_125i</name>
   <tag></tag>
   <elementGuidId>d481fcf6-0aee-40c8-ab8c-1f01f64f4983</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='sq_125i']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sq_125i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d561dba3-b840-4dd9-a82f-0e3dfea0a7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sq_125i</value>
      <webElementGuid>3cd27e60-b943-4ed0-bf7c-0fa1e75dc33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d2396d47-9905-443d-9ee6-d1c44b37abf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>64b5d025-64cc-4bb8-8a10-fc98358e2a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type here…</value>
      <webElementGuid>f9a16aa3-5e4d-448d-98d4-2e1858bd4aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>29af3b7f-0edf-4853-9f4f-8fd9492ff734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>&lt;strong>My Unfinished Business&lt;/strong></value>
      <webElementGuid>28da7585-f237-4d27-ac39-9d05599c33a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>781716fe-b2ff-428f-9f95-016b0162eff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sq_125i&quot;)</value>
      <webElementGuid>32d8a1c1-fb58-4bce-82a3-2204dd5d3382</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='sq_125i']</value>
      <webElementGuid>052619a4-ad35-4ef7-838e-6d7c001bab86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sq_125']/div[2]/textarea</value>
      <webElementGuid>7408e0c5-4d70-4da5-87af-444302f87d40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/div/form/div[2]/div/div/div[6]/div/div/div[2]/textarea</value>
      <webElementGuid>35e2a74b-b19a-4022-a583-5666d46660f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'sq_125i' and @placeholder = 'Type here…']</value>
      <webElementGuid>209594ae-27c7-4bd5-8de0-e037b98dd7cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
