<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_If I Were to Pass Away_sq_127i</name>
   <tag></tag>
   <elementGuidId>9ddb4568-cbfb-496b-be09-7df393395a49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='sq_127i']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#sq_127i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ec4e3656-ec58-4c9a-b67a-bb7c6573ded6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sq_127i</value>
      <webElementGuid>4739c83e-378f-4d0f-816b-7e2105fd78d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f07fe268-ec9d-468e-96fc-8bd668dc54c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>34ffa3f9-59ec-45b6-8690-f14b0fd8ccee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type here…</value>
      <webElementGuid>18908116-5b28-4320-a2e4-29580ce0ebb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3aff3f07-673f-4ad6-a9a0-ddc545a0f0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>&lt;strong>If I Were to Pass Away&lt;/strong></value>
      <webElementGuid>09277868-f691-4ca0-b717-7fce17fb7433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8a669c1c-6c8b-48a0-b182-c34d663bd76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sq_127i&quot;)</value>
      <webElementGuid>56455a4a-f1b3-4b1f-8fb6-7caf3e715918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='sq_127i']</value>
      <webElementGuid>4f3c05d3-8d1f-496f-b282-8c8adb6821fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sq_127']/div[2]/textarea</value>
      <webElementGuid>bf214b55-cdbe-4b64-8bf1-85e580682591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]/textarea</value>
      <webElementGuid>f2ec9df0-74cd-4856-99d5-880d4af4f000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'sq_127i' and @placeholder = 'Type here…']</value>
      <webElementGuid>c01d9071-884f-4d91-a8f2-3dbb1d9d6ecf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
