<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select a file you want to upload_js-f_a3b290</name>
   <tag></tag>
   <elementGuidId>75d66fc8-736e-46c0-b7f5-068523e45230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='js-file-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#js-file-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6ebde36-de54-49e2-88c7-f68bdd6f9c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>3eb5a8d4-455f-4a15-8c8a-f34fe1a6c468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-file-input</value>
      <webElementGuid>6bfb5b79-a098-4bc9-89ef-982669b47caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-file-input&quot;)</value>
      <webElementGuid>e569162b-e0f7-4e00-8acb-d726053ece4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='js-file-input']</value>
      <webElementGuid>fbb4f294-bf7b-4fe1-944e-a7c789e19b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-upload-container']/input</value>
      <webElementGuid>33e3770c-0d9d-49b9-b7da-c2a3525b4866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>febc185c-fb6c-472e-b49a-ec1b9b464978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'js-file-input']</value>
      <webElementGuid>76b11810-7d03-4a0e-bf44-49efcf95b0a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
