<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_00016133</name>
   <tag></tag>
   <elementGuidId>9d8d7e91-a3ed-44ca-919f-c76192b948c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='suggestionsList-470']/search_dialog-instant-result-item/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.slds-text-body--regular.slds-text-color--default.slds-truncate.slds-show</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6b12193e-b5a8-4868-84fb-4d91b3d09fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-text-body--regular slds-text-color--default slds-truncate slds-show</value>
      <webElementGuid>5bbecb7b-c4a7-449e-82a1-bcd8017e6833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>00016133</value>
      <webElementGuid>0b0f6171-ebed-4853-bdc6-e574354b36e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00016133</value>
      <webElementGuid>6bbafb85-4573-4eb0-8568-1769392f2eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suggestionsList-470&quot;)/search_dialog-instant-result-item[1]/div[@class=&quot;slds-text-link--reset slds-grid slds-grid--vertical-align-center slds-truncate instant-result-item slds-p-left_small two-fields instant-result-item-record-suggestion focused&quot;]/div[@class=&quot;slds-truncate instant-result-item__content&quot;]/span[@class=&quot;slds-text-body--regular slds-text-color--default slds-truncate slds-show&quot;]</value>
      <webElementGuid>fdec4e4c-e8ef-4bdc-8c6c-678e1e562b6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suggestionsList-470']/search_dialog-instant-result-item/div/div[2]/span</value>
      <webElementGuid>b18ab5cf-e998-4444-9d3e-060fae2908da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::span[2]</value>
      <webElementGuid>cf95c568-486d-4b50-80fa-b55613e6b725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search Cases and more'])[1]/following::span[3]</value>
      <webElementGuid>3a9f5f06-2808-4d18-8df8-02a507f6717e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case • [Test Only] Change users who can create support tickets'])[1]/preceding::span[2]</value>
      <webElementGuid>33a60362-0e3d-418e-b428-f7f3b18baac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=','])[1]/preceding::span[4]</value>
      <webElementGuid>a5a2701d-fcdb-4404-bcf8-c7c5666409e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//search_dialog-instant-result-item/div/div[2]/span</value>
      <webElementGuid>71563afc-d111-4d63-a043-fe5f880ef467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '00016133' and (text() = '00016133' or . = '00016133')]</value>
      <webElementGuid>629471cb-78ab-4b3b-9880-c9384b5a9192</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
