<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_00016133</name>
   <tag></tag>
   <elementGuidId>b9bbdd20-1637-4c53-bf6a-b006ace29a0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='suggestionsList-470']/search_dialog-instant-result-item[3]/div/div[2]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.slds-text-link--reset.slds-grid.slds-grid--vertical-align-center.slds-truncate.instant-result-item.slds-p-left_small.two-fields.instant-result-item-record-suggestion.focused > div.slds-truncate.instant-result-item__content > span.slds-text-body--regular.slds-text-color--default.slds-truncate.slds-show</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5fe83ccf-9ac4-4218-b191-42fcdbc22e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-text-body--regular slds-text-color--default slds-truncate slds-show</value>
      <webElementGuid>a73cdc01-317f-4ff3-b2f2-3d8d4858a40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>00016133</value>
      <webElementGuid>e46d97bc-fb02-45e5-a9d5-3799b879f040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00016133</value>
      <webElementGuid>26fa9099-d09d-41d6-a459-7f7feba99df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;suggestionsList-470&quot;)/search_dialog-instant-result-item[3]/div[@class=&quot;slds-text-link--reset slds-grid slds-grid--vertical-align-center slds-truncate instant-result-item slds-p-left_small two-fields instant-result-item-record-suggestion focused&quot;]/div[@class=&quot;slds-truncate instant-result-item__content&quot;]/span[@class=&quot;slds-text-body--regular slds-text-color--default slds-truncate slds-show&quot;]</value>
      <webElementGuid>656b7b63-3da3-4404-904c-4ee37e634c28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='suggestionsList-470']/search_dialog-instant-result-item[3]/div/div[2]/span</value>
      <webElementGuid>42496d18-eece-4206-95bd-a6085be975d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='only'])[1]/following::span[3]</value>
      <webElementGuid>f4982d13-b41e-49f3-a42f-3a22646d2421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Test'])[2]/following::span[3]</value>
      <webElementGuid>ac58abdb-9bf9-4aec-9100-687e2041e27a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Case • [Test Only] Change users who can create support tickets'])[1]/preceding::span[2]</value>
      <webElementGuid>d2cd3cae-876a-45f0-acf0-ab9a86aca9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=','])[1]/preceding::span[4]</value>
      <webElementGuid>84370c7b-bc68-4ebe-a012-83385e674070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//search_dialog-instant-result-item[3]/div/div[2]/span</value>
      <webElementGuid>676bad0d-4ef9-4b99-8473-9b8aa3c38c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = '00016133' and (text() = '00016133' or . = '00016133')]</value>
      <webElementGuid>edc11143-e354-4364-9182-aab35b668ca5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
