<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_qwertyuiop_</name>
   <tag></tag>
   <elementGuidId>a7d8166b-f387-48ed-8df6-c130fdc75a40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[dir=&quot;ltr&quot;]:nth-child(2) div:nth-child(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@dir = 'ltr') and (position() = 2)]//*[(name() = 'div') and (position() = 2)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9f2ec1be-5d08-4406-af86-3d9757e181b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>qwertyuiop[]_</value>
      <webElementGuid>99690b87-ceb2-401c-b488-dc4fd0130f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>qwertyuiop[]\</value>
      <webElementGuid>09781b11-daae-468f-9763-99790054a887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-2c3143f36e5c3e4c4f2716cd0507838c</value>
      <webElementGuid>dc065461-fd07-4f91-b5e7-82bcc626381a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@dir = 'ltr') and (position() = 2)]//*[(name() = 'div') and (position() = 2)]</value>
      <webElementGuid>9d7e9239-d593-4017-8159-24ca887a0c7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@dir = 'ltr') and (position() = 2)]//*[(name() = 'div') and (position() = 2)]</value>
      <webElementGuid>39c79d6f-9014-4c2b-9b3d-295bb6f70d12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'qwertyuiop[]_' or . = 'qwertyuiop[]_')]</value>
      <webElementGuid>31f7d575-e6b0-4869-9271-1d63d543f42e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
