<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_btnK</name>
   <tag></tag>
   <elementGuidId>52625148-1235-4dc3-9019-355044ae2b35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[jsname=&quot;VlcLAe&quot;] [name=&quot;btnK&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@jsname = 'VlcLAe']//*[@name = 'btnK']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87201756-80f1-47e7-a6e5-81c41d95242f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gNO89b</value>
      <webElementGuid>7f1a13c1-b2fa-430f-9439-df029245e085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tìm trên Google</value>
      <webElementGuid>1c42ba74-a656-4f85-8c56-e991df05ffdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Tìm trên Google</value>
      <webElementGuid>ed2078e2-aeac-4cea-8bcd-1a0cf7c74aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnK</value>
      <webElementGuid>194af6da-3ad1-4936-85d1-3c81105e7581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca37e333-15ba-4708-80c7-e4d690811f79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bc063287-6349-4f48-885b-fc179b0b8abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f7868d6e-9a44-4199-a310-5082d8ad86d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ved</name>
      <type>Main</type>
      <value>0ahUKEwjb7_LbwZ2KAxUlulYBHVVnCCAQ4dUDCA4</value>
      <webElementGuid>1c47165d-9b4b-4f2f-980a-42eca391b703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>btnK</value>
      <webElementGuid>a395b697-18f7-45ec-bda4-86c9b59138f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-17bcf91289127147caa9c7e252ec1807</value>
      <webElementGuid>cff24cbb-b6ee-43aa-aa8d-449ff759ef04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@jsname = 'VlcLAe']//*[@name = 'btnK']</value>
      <webElementGuid>5d2fdea9-3b31-48ec-871a-3d1a1474d77a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@jsname = 'VlcLAe']//*[@name = 'btnK']</value>
      <webElementGuid>27f1f7a4-6fec-4ce5-8e15-908d7a4487b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'btnK' and @type = 'submit' and (text() = 'btnK' or . = 'btnK')]</value>
      <webElementGuid>10e71ee1-824b-4bfc-90cd-a8dfed6d058f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' FPdoLc ')]//*[@name = 'btnK']</value>
      <webElementGuid>0c047b22-d4e8-473d-b8fe-202bc9e545ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
