<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_t</name>
   <tag></tag>
   <elementGuidId>02f35654-8371-4a86-89dc-f0c7b3f9c3d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.vk-sf-h.vk-cap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' vk-sf-h ') and contains(concat(' ', normalize-space(@class), ' '), ' vk-cap ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c04592e6-6c50-43dc-9d8f-c19dea7e77d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vk-cap vk-sf-h</value>
      <webElementGuid>40a74aef-21e3-46f7-bfba-1d811b0027a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>t</value>
      <webElementGuid>f8d3343a-50d4-4762-a004-fdd477158fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>e</value>
      <webElementGuid>0a3174c5-5415-4758-8686-7fcd02bec665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b0f95bee325b5d3ee581ade27e220ade</value>
      <webElementGuid>042b4e87-4382-4eeb-98f6-00ed8458354f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' vk-sf-h ') and contains(concat(' ', normalize-space(@class), ' '), ' vk-cap ')]</value>
      <webElementGuid>9cd93885-440b-48c3-ac5b-881392e64b97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' vk-sf-h ') and contains(concat(' ', normalize-space(@class), ' '), ' vk-cap ')]</value>
      <webElementGuid>ffbe8db1-30ce-4dfa-92a5-0f58e05b5c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 't' or . = 't')]</value>
      <webElementGuid>70588ae4-71c9-4b20-bb1b-b5fd80cbc531</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
