<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ly0Ckb</name>
   <tag></tag>
   <elementGuidId>eefc2adb-d917-43ea-8d53-b5e89b90b003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-label=&quot;Công\ cụ\ nhập&quot;] span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-label = 'Công cụ nhập']//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f16717bf-c142-4ff0-95f5-3c99a51001af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ly0Ckb</value>
      <webElementGuid>f0d86944-3384-4806-b2a9-281cfb3e9211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ly0Ckb</value>
      <webElementGuid>61db3753-41f8-4e65-84cf-1168521f0ff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1e003584524d3401f02970c97f2121da</value>
      <webElementGuid>0a909114-95b3-4f1c-9b34-0e14c07574d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Công cụ nhập']//span</value>
      <webElementGuid>ad274544-d08b-4416-b057-733fa7933f84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-label = 'Công cụ nhập']//span</value>
      <webElementGuid>efe47419-3ef4-40a1-bfb8-869a0ec704c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ly0Ckb' or . = 'ly0Ckb')]</value>
      <webElementGuid>3d5ef3c5-a6d8-42af-bdfa-39520ff96185</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
