<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mua vi s lng 1000 ci tr ln</name>
   <tag></tag>
   <elementGuidId>e2075fbf-d99e-4750-8e3e-b73f43e0e79b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.btn-special</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-special ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value></value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a6370aea-e146-4cbd-a94e-719fc54dd153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-special</value>
      <webElementGuid>05f38aaf-6b46-455f-a00d-130848e3cca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mua-hang/</value>
      <webElementGuid>69e8a809-25b6-42ae-ac6a-18018dcaffb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mua với số lượng 1000 cái trở lên</value>
      <webElementGuid>f12186f2-d4ce-485f-a048-fed089cbcbf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>@text</name>
      <type>Main</type>
      <value>Mua với số lượng 1000 cái trở lên</value>
      <webElementGuid>1722218b-ed9a-4158-91f1-f8194caa9b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-50fbabc9ca6d468609a76936c2179baa</value>
      <webElementGuid>09234b03-84d1-49ff-a780-c6e05519a975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-special ')]</value>
      <webElementGuid>d5d912f1-70e5-404f-a205-701442ebd36a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' btn-special ')]</value>
      <webElementGuid>8c100c56-16e5-431b-80bb-0978731c8dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mua-hang/' and (text() = 'Mua với số lượng 1000 cái trở lên' or . = 'Mua với số lượng 1000 cái trở lên')]</value>
      <webElementGuid>c2f21c88-f05b-40a1-b044-b03a5a8d5bab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
