<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone number_phoneInputphone-login</name>
   <tag></tag>
   <elementGuidId>50cf73a3-7987-4aba-916b-19b76d47d973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phoneInputphone-login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#phoneInputphone-login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;login-signup-phonenumber&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a94e1581-9f55-47c1-8bdf-6e4061fb1078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>90221b2f-445e-41ef-8b8c-48349474edfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phoneInputphone-login</value>
      <webElementGuid>682e9022-2902-4ca9-b988-7faee7b18ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aa6b6de4-a661-4963-b6ff-24b1f5c5614f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>login-signup-phonenumber</value>
      <webElementGuid>e78408bc-3036-48d8-b988-cbfd3a2ed3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>i1rzcbc6 atm_vy_1osqo2v atm_3f_glywfm atm_kd_glywfm atm_l8_idpfg4 atm_gi_1mn94vf atm_7l_1kw7nm4 atm_2d_1j28jx2 atm_bx_1kw7nm4 atm_c8_1kw7nm4 atm_cs_1kw7nm4 atm_g3_1kw7nm4 atm_1u_glywfm atm_72_f9n0m_1xv0ngy atm_72_f9n0m_ugfzj1 atm_72_f9n0m_15xgy2b atm_72_f9n0m_gk089o atm_9s_glywfm_136h51u atm_7l_1he744i_17x46du atm_k4_kb7nvz_17x46du atm_7l_1he744i_y5ttn9 atm_k4_kb7nvz_y5ttn9 atm_7l_1he744i_1k1obal atm_k4_kb7nvz_1k1obal atm_7l_1he744i_m14rgb atm_k4_kb7nvz_m14rgb atm_7l_1he744i_3ykvna atm_k4_kb7nvz_3ykvna atm_7l_jt7fhx_pfnrn2 atm_1s_glywfm_1343f1v atm_gi_idpfg4_1343f1v dir dir-ltr</value>
      <webElementGuid>3cdb65c8-ffe1-4520-b672-faf3201ef4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneInputphone-login</value>
      <webElementGuid>02f546d7-8107-4f27-8d97-1064f5f9d4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>tel-national</value>
      <webElementGuid>5cc861f6-2676-4e97-a844-3948f9e3f13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>1840f8b2-4e28-40fc-ae13-6604c87ff855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>phone-number-help-text-phone-login airlock-inline-container</value>
      <webElementGuid>231e95f0-916e-4f6c-9794-b51761d1e255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneInputphone-login&quot;)</value>
      <webElementGuid>ccbece5b-04e8-4642-8ed3-4ee9aa384bb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phoneInputphone-login']</value>
      <webElementGuid>2274329f-7a62-4d08-8a0f-9cb827efcb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div[2]/input</value>
      <webElementGuid>ef6b1b7e-1650-4397-a91b-32257ba2ef11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'phoneInputphone-login' and @id = 'phoneInputphone-login' and @type = 'tel']</value>
      <webElementGuid>b1367825-d466-4c98-890f-79108076647f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
